.TH chromium 6 "Aug 3 2001"
.SH NAME
chromium \- slick scrolling space shooter
.SH SYNOPSIS
.B chromium
[\-fwv] [\-na] [\-nb] [\-nt]
[\-\-fullscreen] [\-\-window] [\-\-vidmode <mode>]
[\-\-noaudio] [\-\-noblend] [\-\-notexborder]
.SH DESCRIPTION
\fBchromium\fP is a fast paced top down arcade style action shooter game.
You progress through the game by destroying everything that you see on
screen. There are a variety of 'power-ups' to assist you on the way.
There is a big boss to destroy at the end of each level and there are
various ships to destroy before you reach each boss.
.SH TIPS
Do not let ANY enemy ships get past your fighters!
.TP
Use your fighters as weapons!
.TP
Strategic suicide is a powerful tactic!
.TP
Self-destruct to preserve your ammunition! 
.SH OPTIONS
When run with arguments that are not understood, usage information is shown.
.TP
.B chromium
understands the following command line options
.TP
.B \-f \-\-fullscreen
runs in fullscreen mode.
.TP
.B \-w \-\-window
runs in a window.
.TP
.B \-na \-\-noaudio
does not initialize audio.
.TP
.B \-v <mode>, \-\-vidmode <mode>
selects video mode.
.br
mode
.br
0 =  512 x  384
.br
1 =  640 x  480
.br
2 =  800 x  600
.br
3 = 1024 x  768
.br
4 = 1280 x 1024
.TP
.B \-nb \-\-noblend 
disables blending. (OpenGL)
.TP
.B \-nt \-\-notexborder 
do not set tex border color. (OpenGL)
.SH ENVIRONMENT
The following environment variables are used by chromium.
.TP
.B CHROMIUM_SCORE
specifies the location of the user high-score file.
.TP
.B CHROMIUM_DATA
specifies the location of user-customised game data with the same layout and filenames as the system one.
.TP
.B CHROMIUM_FONT
specifies the location of the font used in the menu and the game.
.SH FILES
The following files are used by chromium.
.TP
.I "~/.chromium"
contains various chromium user preferences.
.TP
.I "~/.chromium-score"
contains the chromium user high-scores.
.TP
.I "~/.chromium-music"
contains a list of music to play during the game.
.TP
.I "~/.chromium-data/"
directory containing user-customized game data with the same layout and filenames as the system one.
.TP
Chromium will also look in a system directory for data.
.SH SEE ALSO
.br
"In game procedures and flight safety"
.SH AUTHOR
This manual page was written by Peter Joseph <kneecaps@debian.org>,
for the Debian GNU/Linux system.
